//! # Vesting
//!
//! Linear token vesting with an optional cliff and optional revocation, for any
//! SEP-41 token on Soroban. One deployed contract holds any number of fully
//! isolated schedules.
//!
//! See `docs/ARCHITECTURE.md` for the design and `docs/SECURITY-MODEL.md` for
//! the threat model.
#![no_std]
// `create_schedule` mirrors the schedule's fields one-to-one. The client and
// spec code generated by `#[contractimpl]` trips this lint at the module level.
#![allow(clippy::too_many_arguments)]

mod error;
mod events;
mod math;
mod storage;
mod types;

#[cfg(test)]
mod test;

use soroban_sdk::{contract, contractimpl, token::TokenClient, Address, Env};

pub use error::Error;
pub use types::Schedule;

use events::{Claimed, Revoked, ScheduleCreated};

#[contract]
pub struct VestingContract;

#[contractimpl]
impl VestingContract {
    /// Lock `amount` of `token` from `funder` and start a schedule for
    /// `beneficiary`. Returns the new schedule id (ids start at 0).
    ///
    /// Requires `funder` authorization. Timestamps are ledger-time seconds and
    /// must satisfy `start <= cliff <= end` and `start < end`.
    pub fn create_schedule(
        env: Env,
        funder: Address,
        beneficiary: Address,
        token: Address,
        amount: i128,
        start: u64,
        cliff: u64,
        end: u64,
        revocable: bool,
    ) -> Result<u64, Error> {
        funder.require_auth();

        if amount <= 0 {
            return Err(Error::InvalidAmount);
        }
        if start >= end || cliff < start || cliff > end {
            return Err(Error::InvalidSchedule);
        }

        let id = storage::count(&env);
        let schedule = Schedule {
            funder: funder.clone(),
            beneficiary: beneficiary.clone(),
            token: token.clone(),
            total: amount,
            claimed: 0,
            start,
            cliff,
            end,
            revocable,
            revoked: false,
            vested_at_revoke: 0,
        };

        // Effects before interaction.
        storage::save(&env, id, &schedule);
        storage::set_count(&env, id + 1);
        storage::extend_instance(&env);
        storage::extend_schedule(&env, id);

        TokenClient::new(&env, &token).transfer(&funder, env.current_contract_address(), &amount);

        ScheduleCreated {
            id,
            beneficiary,
            funder,
            token,
            amount,
            start,
            cliff,
            end,
            revocable,
        }
        .publish(&env);

        Ok(id)
    }

    /// Withdraw everything that has vested and not yet been claimed.
    /// Requires the beneficiary's authorization. Returns the amount paid out.
    pub fn claim(env: Env, id: u64) -> Result<i128, Error> {
        let mut schedule = storage::load(&env, id)?;
        schedule.beneficiary.require_auth();

        let amount = Self::claimable_of(&env, &schedule)?;
        if amount <= 0 {
            return Err(Error::NothingToClaim);
        }

        schedule.claimed += amount;
        storage::save(&env, id, &schedule);
        storage::extend_instance(&env);
        storage::extend_schedule(&env, id);

        TokenClient::new(&env, &schedule.token).transfer(
            &env.current_contract_address(),
            &schedule.beneficiary,
            &amount,
        );

        Claimed {
            id,
            beneficiary: schedule.beneficiary,
            amount,
        }
        .publish(&env);

        Ok(amount)
    }

    /// Stop vesting and return the unvested remainder to the funder.
    /// Whatever had vested so far stays claimable by the beneficiary.
    /// Requires the funder's authorization. Returns the refunded amount.
    pub fn revoke(env: Env, id: u64) -> Result<i128, Error> {
        let mut schedule = storage::load(&env, id)?;
        schedule.funder.require_auth();

        if !schedule.revocable {
            return Err(Error::NotRevocable);
        }
        if schedule.revoked {
            return Err(Error::AlreadyRevoked);
        }

        let vested = Self::vested_of(&env, &schedule)?;
        let refund = schedule.total - vested;

        schedule.revoked = true;
        schedule.vested_at_revoke = vested;
        storage::save(&env, id, &schedule);
        storage::extend_instance(&env);
        storage::extend_schedule(&env, id);

        if refund > 0 {
            TokenClient::new(&env, &schedule.token).transfer(
                &env.current_contract_address(),
                &schedule.funder,
                &refund,
            );
        }

        Revoked {
            id,
            funder: schedule.funder,
            refunded: refund,
            vested,
        }
        .publish(&env);

        Ok(refund)
    }

    /// Permissionless: extend the storage lifetime of the contract and of
    /// schedule `id`, so a long-running schedule never has to be restored.
    pub fn bump(env: Env, id: u64) -> Result<(), Error> {
        // Existence check first so a bad id fails loudly instead of trapping.
        storage::load(&env, id)?;
        storage::extend_instance(&env);
        storage::extend_schedule(&env, id);
        Ok(())
    }

    /// Total vested so far (claimed or not). Read-only.
    pub fn vested_amount(env: Env, id: u64) -> Result<i128, Error> {
        let schedule = storage::load(&env, id)?;
        Self::vested_of(&env, &schedule)
    }

    /// Vested minus already claimed. Read-only.
    pub fn claimable(env: Env, id: u64) -> Result<i128, Error> {
        let schedule = storage::load(&env, id)?;
        Self::claimable_of(&env, &schedule)
    }

    /// Full schedule record. Read-only.
    pub fn get_schedule(env: Env, id: u64) -> Result<Schedule, Error> {
        storage::load(&env, id)
    }

    /// How many schedules this contract has ever created. Read-only.
    pub fn schedule_count(env: Env) -> u64 {
        storage::count(&env)
    }
}

impl VestingContract {
    fn vested_of(env: &Env, s: &Schedule) -> Result<i128, Error> {
        if s.revoked {
            return Ok(s.vested_at_revoke);
        }
        math::vested(s.total, s.start, s.cliff, s.end, env.ledger().timestamp())
    }

    fn claimable_of(env: &Env, s: &Schedule) -> Result<i128, Error> {
        Ok(Self::vested_of(env, s)? - s.claimed)
    }
}
