#!/usr/bin/env bash
# End-to-end demo on Stellar testnet using native XLM.
# Deploys the contract, creates a revocable schedule, claims, revokes, and
# claims the vested remainder. Writes docs/testnet-proof.md.
#
# Requires: stellar CLI, the wasm32v1-none Rust target, network access.
set -euo pipefail
cd "$(dirname "$0")/.."

NET=testnet
FUNDER=vesting-funder
BENEF=vesting-beneficiary
AMOUNT=1000000000          # 100 XLM in stroops
PROOF=docs/testnet-proof.md

need() { command -v "$1" >/dev/null || { echo "missing dependency: $1" >&2; exit 1; }; }
need stellar

hash_of() { grep -oE '[0-9a-f]{64}' | head -1 || true; }

echo "==> Build"
stellar contract build
WASM=target/wasm32v1-none/release/vesting.wasm
[ -f "$WASM" ] || WASM=$(find target -name vesting.wasm -path '*release*' | head -1)

echo "==> Identities"
for k in "$FUNDER" "$BENEF"; do
  stellar keys address "$k" >/dev/null 2>&1 || stellar keys generate "$k" --network "$NET" --fund
done
FUNDER_ADDR=$(stellar keys address "$FUNDER")
BENEF_ADDR=$(stellar keys address "$BENEF")

echo "==> Deploy"
DEPLOY_LOG=$(stellar contract deploy --wasm "$WASM" --source "$FUNDER" --network "$NET" 2>&1 | tee /dev/stderr)
CONTRACT=$(echo "$DEPLOY_LOG" | grep -oE 'C[A-Z2-7]{55}' | tail -1)
DEPLOY_TX=$(echo "$DEPLOY_LOG" | hash_of)
WASM_HASH=$(sha256sum "$WASM" | cut -d' ' -f1)
TOKEN=$(stellar contract id asset --asset native --network "$NET")

NOW=$(date +%s)
START=$((NOW - 1000)); CLIFF=$((NOW - 500)); END=$((NOW + 1000))

invoke() { # invoke <source> <fn> [args...]
  local src=$1; shift
  stellar contract invoke --id "$CONTRACT" --source "$src" --network "$NET" -- "$@" 2>&1 | tee /dev/stderr
}

echo "==> create_schedule"
OUT=$(invoke "$FUNDER" create_schedule --funder "$FUNDER_ADDR" --beneficiary "$BENEF_ADDR" \
  --token "$TOKEN" --amount "$AMOUNT" --start "$START" --cliff "$CLIFF" --end "$END" --revocable true)
CREATE_TX=$(echo "$OUT" | hash_of)

echo "==> claim (partial)"
OUT=$(invoke "$BENEF" claim --id 0)
CLAIM_TX=$(echo "$OUT" | hash_of)
CLAIM1=$(echo "$OUT" | grep -oE '"[0-9]+"' | tail -1 | tr -d '"')

echo "==> revoke"
OUT=$(invoke "$FUNDER" revoke --id 0)
REVOKE_TX=$(echo "$OUT" | hash_of)
REFUND=$(echo "$OUT" | grep -oE '"[0-9]+"' | tail -1 | tr -d '"')

echo "==> claim vested remainder"
OUT=$(invoke "$BENEF" claim --id 0 || true)
CLAIM2_TX=$(echo "$OUT" | hash_of)

link() { [ -n "${1:-}" ] && echo "[\`${1:0:12}...\`](https://stellar.expert/explorer/testnet/tx/$1)" || echo "see script output"; }

cat > "$PROOF" <<DOC
# Testnet proof

Generated by \`scripts/demo-testnet.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).

| Item | Value |
|---|---|
| Network | Testnet |
| Contract ID | [\`$CONTRACT\`](https://stellar.expert/explorer/testnet/contract/$CONTRACT) |
| WASM sha256 | \`$WASM_HASH\` |
| Token | native XLM (\`$TOKEN\`) |
| Funder | \`$FUNDER_ADDR\` |
| Beneficiary | \`$BENEF_ADDR\` |

| Step | Result | Transaction |
|---|---|---|
| deploy | contract created | $(link "$DEPLOY_TX") |
| create_schedule | 100 XLM locked (revocable) | $(link "$CREATE_TX") |
| claim | paid ${CLAIM1:-?} stroops | $(link "$CLAIM_TX") |
| revoke | refunded ${REFUND:-?} stroops to funder | $(link "$REVOKE_TX") |
| claim after revoke | pays what vested between the first claim and the revoke, or fails with NothingToClaim if nothing did | $(link "$CLAIM2_TX") |
DOC

echo "==> Wrote $PROOF"
